database:
  host: "localhost"
  port: 5430
  name: "postgres"
  username: "postgres"
  password: "postgres"
  tls:
    enabled: false
    trusted_root_certs: ""
  require_ssl: false
application:
  host: "127.0.0.1"
  port: 8000
encryption_key:
  id: 0
  key: BlK9AlrzqRnCZy53j42uE1p2qGBiF7HYZjZYFaZObqg=
api_key: XOUbHmWbt9h7nWl15wWwyWQnctmFGNjpawMc3lT5CFs=
