//! Gitignored API configuration generation.

use std::fs;

use anyhow::{Context, Result};
use base64::{Engine, engine::general_purpose::STANDARD as BASE64};
use rand::RngCore;

use crate::commands::{
    local::InitConfig,
    setup::{api_config_dir, ensure_config_dir, write_file, yaml_string},
};

/// Generated API base configuration.
const API_BASE_YAML: &str = "\
# Generated by `cargo x setup api`. Gitignored. Do not commit.
{}\n";

/// Writes gitignored local API configuration when missing, or when `force` is
/// set.
pub(super) fn write_api_config(config: &InitConfig, force: bool) -> Result<()> {
    let directory = api_config_dir()?;
    ensure_config_dir(&directory)?;

    write_file(&directory.join("base.yaml"), API_BASE_YAML, force)?;
    let dev_path = directory.join("dev.yaml");
    if dev_path.is_file() && !force {
        let existing = fs::read_to_string(&dev_path)
            .with_context(|| format!("Failed to read {}", dev_path.display()))?;
        if !existing.contains("internal_port:") {
            let updated = insert_internal_port(&existing);
            fs::write(&dev_path, updated)
                .with_context(|| format!("Failed to update {}", dev_path.display()))?;
            println!("🔧 Updated {} with application.internal_port: 8081", dev_path.display());
        } else {
            println!("♻️  Keeping existing {}", dev_path.display());
        }
    } else {
        let encryption_key = random_base64(32)?;
        let api_key = random_base64(32)?;
        let existing = if dev_path.is_file() {
            Some(
                fs::read_to_string(&dev_path)
                    .with_context(|| format!("Failed to read {}", dev_path.display()))?,
            )
        } else {
            None
        };
        let encryption_keys = encryption_keys_yaml(existing.as_deref(), &encryption_key)?;
        let contents = api_dev_yaml(config, &encryption_keys, &api_key);
        fs::write(&dev_path, contents)
            .with_context(|| format!("Failed to write {}", dev_path.display()))?;
        println!("📝 Wrote {}", dev_path.display());
    }

    Ok(())
}

/// Renders a new keyring or appends a key to the existing generated keyring.
fn encryption_keys_yaml(existing: Option<&str>, new_key: &str) -> Result<String> {
    let Some(existing) = existing else {
        return Ok(format!("encryption_keys:\n  - id: 0\n    key: {}", yaml_string(new_key)));
    };

    let mut lines = existing.lines();
    let Some(_) = lines.find(|line| *line == "encryption_keys:") else {
        anyhow::bail!("Existing API configuration has no encryption_keys section");
    };

    let mut key_lines = Vec::new();
    let mut key_ids = Vec::new();
    for line in lines {
        if !line.is_empty() && !line.starts_with([' ', '\t']) {
            break;
        }
        if let Some(id) = line.trim().strip_prefix("- id:") {
            key_ids.push(id.trim().parse::<u32>().context("Invalid encryption key id")?);
        }
        key_lines.push(line);
    }

    let latest_key_id = key_ids
        .into_iter()
        .max()
        .context("Existing API configuration has no encryption key entries")?;
    let new_key_id =
        latest_key_id.checked_add(1).context("Encryption key id cannot be incremented")?;

    let mut yaml = String::from("encryption_keys:\n");
    for line in key_lines {
        yaml.push_str(line);
        yaml.push('\n');
    }
    yaml.push_str(&format!("  - id: {new_key_id}\n    key: {}", yaml_string(new_key)));
    Ok(yaml)
}

/// Inserts `internal_port` into an older local API config that predates it.
fn insert_internal_port(contents: &str) -> String {
    let mut result = String::new();
    let mut in_application = false;
    let mut inserted = false;

    for line in contents.lines() {
        let trimmed = line.trim();
        if trimmed == "application:" {
            in_application = true;
        } else if !line.starts_with([' ', '\t']) && !trimmed.is_empty() && !trimmed.starts_with('#')
        {
            in_application = false;
        }

        result.push_str(line);
        result.push('\n');

        if in_application && !inserted && trimmed.starts_with("port:") {
            let indent = line.chars().take_while(|character| *character == ' ').count();
            result.push_str(&format!("{:indent$}internal_port: 8081\n", "", indent = indent));
            inserted = true;
        }
    }

    if !inserted {
        result.push_str("\napplication:\n  internal_port: 8081\n");
    }

    result
}

/// Returns `len` random bytes encoded as standard Base64.
fn random_base64(len: usize) -> Result<String> {
    let mut bytes = vec![0u8; len];
    rand::rng().fill_bytes(&mut bytes);
    Ok(BASE64.encode(bytes))
}

/// Renders the generated API `dev.yaml`.
///
/// Only required fields are written. Serde defaults (namespace, VPA bounds,
/// Vector image, keepalive, and optional integrations) stay in code.
fn api_dev_yaml(config: &InitConfig, encryption_keys: &str, api_key: &str) -> String {
    format!(
        "\
# Generated by `cargo x setup api`. Gitignored. Do not commit.
# Encryption and API keys are created locally. `--force` preserves old encryption keys and adds a \
         new id.
# Postgres password is the published `cargo x init` Docker default.
database:
  host: {host}
  port: {port}
  name: {name}
  username: {username}
  password: {password}
  tls:
    enabled: false
    trusted_root_certs: \"\"
application:
  host: \"127.0.0.1\"
  port: 8010
  internal_port: 8081
k8s:
  replicator_resources:
    cpu_request_millicores: 2000
    memory_request_mib: 8192
  vector_resources:
    cpu_request_millicores: 75
    memory_request_mib: 192
source:
  tls:
    enabled: false
    trusted_root_certs: \"\"
{encryption_keys}
api_keys:
  - {api_key}
",
        host = yaml_string(&config.db_host),
        port = config.db_port,
        name = yaml_string(&config.db_name),
        username = yaml_string(&config.db_user),
        password = yaml_string(&config.db_password),
        encryption_keys = encryption_keys,
        api_key = yaml_string(api_key),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn unique_temp_dir(label: &str) -> std::path::PathBuf {
        std::env::temp_dir().join(format!(
            "etl-xtask-{label}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
        ))
    }

    #[test]
    fn api_dev_yaml_loads_with_generated_keys() {
        let encryption_key = BASE64.encode([0u8; 32]);
        let api_key = BASE64.encode([1u8; 32]);
        let encryption_keys = encryption_keys_yaml(None, &encryption_key).unwrap();
        let yaml = api_dev_yaml(&InitConfig::from_env(), &encryption_keys, &api_key);
        assert!(yaml.contains("internal_port: 8081"));

        let directory = unique_temp_dir("api-config");
        fs::create_dir_all(&directory).unwrap();
        fs::write(directory.join("base.yaml"), API_BASE_YAML).unwrap();
        fs::write(directory.join("dev.yaml"), yaml).unwrap();
        // SAFETY: nextest runs each test in its own process.
        unsafe {
            std::env::set_var("APP_ENVIRONMENT", "dev");
            std::env::set_var("APP_CONFIG_DIR", &directory);
        }
        etl_config::load_config::<etl_api::config::ApiConfig>()
            .expect("generated API config should load");
        let _ = fs::remove_dir_all(&directory);
    }

    #[test]
    fn force_adds_new_encryption_key_without_replacing_old_key() {
        let old_key = BASE64.encode([0u8; 32]);
        let new_key = BASE64.encode([1u8; 32]);
        let api_key = BASE64.encode([2u8; 32]);
        let initial_keys = encryption_keys_yaml(None, &old_key).unwrap();
        let initial_yaml = api_dev_yaml(&InitConfig::from_env(), &initial_keys, &api_key);

        let rotated_keys = encryption_keys_yaml(Some(&initial_yaml), &new_key).unwrap();
        let rotated_yaml = api_dev_yaml(&InitConfig::from_env(), &rotated_keys, &api_key);

        assert!(rotated_keys.contains("  - id: 0"));
        assert!(rotated_keys.contains(&yaml_string(&old_key)));
        assert!(rotated_keys.contains("  - id: 1"));
        assert!(rotated_keys.contains(&yaml_string(&new_key)));

        let directory = unique_temp_dir("rotated-api-config");
        fs::create_dir_all(&directory).unwrap();
        fs::write(directory.join("base.yaml"), API_BASE_YAML).unwrap();
        fs::write(directory.join("dev.yaml"), rotated_yaml).unwrap();
        // SAFETY: nextest runs each test in its own process.
        unsafe {
            std::env::set_var("APP_ENVIRONMENT", "dev");
            std::env::set_var("APP_CONFIG_DIR", &directory);
        }
        let config = etl_config::load_config::<etl_api::config::ApiConfig>().unwrap();
        let _ = fs::remove_dir_all(&directory);

        assert_eq!(config.encryption_keys.len(), 2);
    }
}
