//! Gitignored API configuration generation.

use std::fs;

use anyhow::{Context, Result};
use base64::{Engine, engine::general_purpose::STANDARD as BASE64};
use rand::RngCore;

use crate::commands::{
    local::InitConfig,
    setup::{api_config_dir, ensure_config_dir, write_file, yaml_string},
};

/// Generated API base configuration.
const API_BASE_YAML: &str = "\
# Generated by `cargo x setup api`. Gitignored. Do not commit.
{}\n";

/// Writes gitignored local API configuration when missing, or when `force` is
/// set.
pub(super) fn write_api_config(config: &InitConfig, force: bool) -> Result<()> {
    let directory = api_config_dir()?;
    ensure_config_dir(&directory)?;

    write_file(&directory.join("base.yaml"), API_BASE_YAML, force)?;
    let dev_path = directory.join("dev.yaml");
    if dev_path.is_file() && !force {
        let existing = fs::read_to_string(&dev_path)
            .with_context(|| format!("Failed to read {}", dev_path.display()))?;
        if !existing.contains("internal_port:") {
            let updated = insert_internal_port(&existing);
            fs::write(&dev_path, updated)
                .with_context(|| format!("Failed to update {}", dev_path.display()))?;
            println!("🔧 Updated {} with application.internal_port: 8081", dev_path.display());
        } else {
            println!("♻️  Keeping existing {}", dev_path.display());
        }
    } else {
        let encryption_key = random_base64(32)?;
        let api_key = random_base64(32)?;
        let contents = api_dev_yaml(config, &encryption_key, &api_key);
        fs::write(&dev_path, contents)
            .with_context(|| format!("Failed to write {}", dev_path.display()))?;
        println!("📝 Wrote {}", dev_path.display());
    }

    Ok(())
}

/// Inserts `internal_port` into an older local API config that predates it.
fn insert_internal_port(contents: &str) -> String {
    let mut result = String::new();
    let mut in_application = false;
    let mut inserted = false;

    for line in contents.lines() {
        let trimmed = line.trim();
        if trimmed == "application:" {
            in_application = true;
        } else if !line.starts_with([' ', '\t']) && !trimmed.is_empty() && !trimmed.starts_with('#')
        {
            in_application = false;
        }

        result.push_str(line);
        result.push('\n');

        if in_application && !inserted && trimmed.starts_with("port:") {
            let indent = line.chars().take_while(|character| *character == ' ').count();
            result.push_str(&format!("{:indent$}internal_port: 8081\n", "", indent = indent));
            inserted = true;
        }
    }

    if !inserted {
        result.push_str("\napplication:\n  internal_port: 8081\n");
    }

    result
}

/// Returns `len` random bytes encoded as standard Base64.
fn random_base64(len: usize) -> Result<String> {
    let mut bytes = vec![0u8; len];
    rand::rng().fill_bytes(&mut bytes);
    Ok(BASE64.encode(bytes))
}

/// Renders the generated API `dev.yaml`.
///
/// Only required fields are written. Serde defaults (namespace, VPA bounds,
/// Vector image, keepalive, and optional integrations) stay in code.
fn api_dev_yaml(config: &InitConfig, encryption_key: &str, api_key: &str) -> String {
    format!(
        "\
# Generated by `cargo x setup api`. Gitignored. Do not commit.
# Encryption and API keys are created locally. Re-run with `--force` to rotate.
# Postgres password is the published `cargo x init` Docker default.
database:
  host: {host}
  port: {port}
  name: {name}
  username: {username}
  password: {password}
  tls:
    enabled: false
    trusted_root_certs: \"\"
application:
  host: \"127.0.0.1\"
  port: 8010
  internal_port: 8081
k8s:
  replicator_resources:
    cpu_request_millicores: 2000
    memory_request_mib: 8192
  vector_resources:
    cpu_request_millicores: 75
    memory_request_mib: 192
source:
  tls:
    enabled: false
    trusted_root_certs: \"\"
encryption_keys:
  - id: 0
    key: {encryption_key}
api_keys:
  - {api_key}
",
        host = yaml_string(&config.db_host),
        port = config.db_port,
        name = yaml_string(&config.db_name),
        username = yaml_string(&config.db_user),
        password = yaml_string(&config.db_password),
        encryption_key = yaml_string(encryption_key),
        api_key = yaml_string(api_key),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn unique_temp_dir(label: &str) -> std::path::PathBuf {
        std::env::temp_dir().join(format!(
            "etl-xtask-{label}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
        ))
    }

    #[test]
    fn api_dev_yaml_loads_with_generated_keys() {
        let encryption_key = BASE64.encode([0u8; 32]);
        let api_key = BASE64.encode([1u8; 32]);
        let yaml = api_dev_yaml(&InitConfig::from_env(), &encryption_key, &api_key);
        assert!(yaml.contains("internal_port: 8081"));

        let directory = unique_temp_dir("api-config");
        fs::create_dir_all(&directory).unwrap();
        fs::write(directory.join("base.yaml"), API_BASE_YAML).unwrap();
        fs::write(directory.join("dev.yaml"), yaml).unwrap();
        // SAFETY: nextest runs each test in its own process.
        unsafe {
            std::env::set_var("APP_ENVIRONMENT", "dev");
            std::env::set_var("APP_CONFIG_DIR", &directory);
        }
        etl_config::load_config::<etl_api::config::ApiConfig>()
            .expect("generated API config should load");
        let _ = fs::remove_dir_all(&directory);
    }
}
