//! Gitignored replicator configuration generation.

use std::{
    env,
    ffi::OsString,
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};
use clap::ValueEnum;
use etl_config::shared::{DestinationConfig, IcebergConfig, ReplicatorConfig};
use secrecy::ExposeSecret;

use crate::{
    commands::{
        local::InitConfig,
        setup::{ensure_config_dir, prompt, replicator_config_dir, write_file, yaml_string},
    },
    utils::DestinationPreset,
};

/// Placeholder accepted by interactive prompts when a secret will be supplied
/// later through the environment.
const REPLACE_ME: &str = "REPLACE_ME";
/// Fake BigQuery service-account JSON used when no key file is supplied.
const PLACEHOLDER_SERVICE_ACCOUNT_KEY: &str = "placeholder-service-account-json";
/// Fake Snowflake private key used in generated local config.
const PLACEHOLDER_SNOWFLAKE_PRIVATE_KEY: &str = "placeholder-private-key";
/// Fake Iceberg Supabase catalog token used in generated local config.
const PLACEHOLDER_ICEBERG_CATALOG_TOKEN: &str = "placeholder-catalog-token";
/// Fake object-storage access key used for cloud destinations.
const PLACEHOLDER_S3_ACCESS_KEY_ID: &str = "placeholder-s3-access-key-id";
/// Fake object-storage secret key used for cloud destinations.
const PLACEHOLDER_S3_SECRET_ACCESS_KEY: &str = "placeholder-s3-secret-access-key";

/// Generated replicator base configuration.
const REPLICATOR_BASE_YAML: &str = "\
# Generated by `cargo x setup replicator`. Gitignored. Do not commit.
# Pipeline and destination settings live in dev.yaml.
{}\n";

/// Iceberg catalog used by generated replicator configuration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub(super) enum IcebergCatalog {
    /// Local Lakekeeper REST catalog from `cargo x init`.
    Rest,
    /// Supabase-hosted Iceberg catalog.
    Supabase,
}

impl IcebergCatalog {
    /// Returns the config key for this catalog kind.
    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::Rest => "rest",
            Self::Supabase => "supabase",
        }
    }

    /// Parses a catalog name from interactive input.
    pub(super) fn parse(selected: &str) -> Result<Self> {
        match selected {
            "rest" => Ok(Self::Rest),
            "supabase" => Ok(Self::Supabase),
            other => bail!("Unknown Iceberg catalog `{other}`. Use rest or supabase."),
        }
    }
}

/// Values used to render a local replicator configuration.
pub(super) struct ReplicatorSetup {
    /// Postgres publication name.
    pub(super) publication: String,
    postgres: SourcePostgres,
    destination: DestinationSetup,
}

/// Source Postgres settings written into generated replicator configuration.
struct SourcePostgres {
    /// Postgres host.
    host: String,
    /// Postgres port.
    port: String,
    /// Postgres database name.
    name: String,
    /// Postgres user.
    username: String,
    /// Postgres password.
    password: String,
}

/// Destination-specific settings that own their rendered fields.
enum DestinationSetup {
    BigQuery {
        project_id: String,
        dataset_id: String,
        service_account_key: String,
    },
    ClickHouse {
        url: String,
        user: String,
        password: String,
    },
    DuckLake {
        catalog_url: String,
        data_path: String,
    },
    Iceberg(IcebergSetup),
    Snowflake {
        account_id: String,
        user: String,
        database: String,
        schema: String,
        private_key: String,
    },
}

/// Iceberg catalog settings that own their rendered fields.
enum IcebergSetup {
    Rest {
        catalog_uri: String,
        warehouse_name: String,
        s3_endpoint: String,
        s3_access_key_id: String,
        s3_secret_access_key: String,
    },
    Supabase {
        project_ref: String,
        warehouse_name: String,
        s3_region: String,
        catalog_token: String,
        s3_access_key_id: String,
        s3_secret_access_key: String,
    },
}

impl ReplicatorSetup {
    /// Builds local connection defaults for `destination`.
    pub(super) fn for_destination(
        config: &InitConfig,
        destination: DestinationPreset,
        iceberg_catalog: IcebergCatalog,
    ) -> Self {
        Self {
            publication: "seed_pub".to_owned(),
            postgres: SourcePostgres {
                host: config.db_host.clone(),
                port: config.db_port.clone(),
                name: "etl_testdata".to_owned(),
                username: config.db_user.clone(),
                password: config.db_password.clone(),
            },
            destination: DestinationSetup::from_defaults(config, destination, iceberg_catalog),
        }
    }

    /// Returns the destination preset represented by this setup.
    pub(super) fn preset(&self) -> DestinationPreset {
        self.destination.preset()
    }

    /// Returns whether setup should wait for the local Iceberg REST catalog.
    pub(super) fn needs_local_iceberg_catalog(&self) -> bool {
        matches!(self.destination, DestinationSetup::Iceberg(IcebergSetup::Rest { .. }))
    }

    /// Replaces the BigQuery service-account key when this setup is BigQuery.
    pub(super) fn set_bigquery_service_account_key(&mut self, key: &str) -> Result<()> {
        match &mut self.destination {
            DestinationSetup::BigQuery { service_account_key, .. } => {
                *service_account_key = key.to_owned();
                Ok(())
            }
            _ => {
                println!("Ignoring --bq-sa-key-file because the destination is not bigquery.");
                Ok(())
            }
        }
    }

    /// Prompts for destination-specific values.
    pub(super) fn prompt_destination(&mut self) -> Result<()> {
        self.postgres.host = prompt("Postgres host", &self.postgres.host)?;
        self.postgres.port = prompt("Postgres port", &self.postgres.port)?;
        self.postgres.name = prompt("Postgres database", &self.postgres.name)?;
        self.postgres.username = prompt("Postgres user", &self.postgres.username)?;
        self.postgres.password = prompt("Postgres password", &self.postgres.password)?;
        self.publication = prompt("Publication name", &self.publication)?;
        self.destination.prompt()
    }

    /// Renders the generated replicator `dev.yaml`.
    fn to_yaml(&self) -> String {
        format!(
            "\
# Generated by `cargo x setup replicator`. Gitignored. Do not commit.
# Only required fields are written; batching and retry defaults stay in code.
# Postgres, ClickHouse, and MinIO passwords are the published `cargo x init` Docker defaults.
# Cloud secrets are fake placeholders. Override them with APP_ environment variables.
{destination}
pipeline:
  id: 1
  publication_name: {publication}
  pg_connection:
    host: {host}
    port: {port}
    name: {name}
    username: {username}
    password: {password}
    tls:
      enabled: false
      trusted_root_certs: \"\"
",
            destination = self.destination.to_yaml().trim_end(),
            publication = yaml_string(&self.publication),
            host = yaml_string(&self.postgres.host),
            port = self.postgres.port,
            name = yaml_string(&self.postgres.name),
            username = yaml_string(&self.postgres.username),
            password = yaml_string(&self.postgres.password),
        )
    }
}

impl DestinationSetup {
    /// Builds destination defaults from local stack settings.
    fn from_defaults(
        config: &InitConfig,
        destination: DestinationPreset,
        iceberg_catalog: IcebergCatalog,
    ) -> Self {
        match destination {
            DestinationPreset::BigQuery => Self::BigQuery {
                project_id: "example-gcp-project".to_owned(),
                dataset_id: "etl_dataset".to_owned(),
                service_account_key: PLACEHOLDER_SERVICE_ACCOUNT_KEY.to_owned(),
            },
            DestinationPreset::ClickHouse => Self::ClickHouse {
                url: format!("http://{}:{}", config.db_host, config.clickhouse_http_port),
                user: config.clickhouse_user.clone(),
                password: config.clickhouse_password.clone(),
            },
            DestinationPreset::DuckLake => Self::DuckLake {
                catalog_url: format!(
                    "postgres://{}:{}@{}:{}/ducklake_catalog",
                    config.db_user, config.db_password, config.db_host, config.db_port
                ),
                data_path: "s3://example-bucket/lake_data".to_owned(),
            },
            DestinationPreset::Iceberg => {
                Self::Iceberg(IcebergSetup::from_catalog(iceberg_catalog))
            }
            DestinationPreset::Snowflake => Self::Snowflake {
                account_id: "exampleorg-exampleaccount".to_owned(),
                user: "etl_user".to_owned(),
                database: "ETL_DEV".to_owned(),
                schema: "PUBLIC".to_owned(),
                private_key: PLACEHOLDER_SNOWFLAKE_PRIVATE_KEY.to_owned(),
            },
        }
    }

    /// Returns the destination preset represented by this setup.
    fn preset(&self) -> DestinationPreset {
        match self {
            Self::BigQuery { .. } => DestinationPreset::BigQuery,
            Self::ClickHouse { .. } => DestinationPreset::ClickHouse,
            Self::DuckLake { .. } => DestinationPreset::DuckLake,
            Self::Iceberg(_) => DestinationPreset::Iceberg,
            Self::Snowflake { .. } => DestinationPreset::Snowflake,
        }
    }

    /// Prompts for destination-specific values.
    fn prompt(&mut self) -> Result<()> {
        match self {
            Self::ClickHouse { url, user, password } => {
                *url = prompt("ClickHouse HTTP URL", url)?;
                *user = prompt("ClickHouse user", user)?;
                *password = prompt("ClickHouse password", password)?;
            }
            Self::BigQuery { project_id, dataset_id, service_account_key } => {
                *project_id = prompt("BigQuery project id", project_id)?;
                *dataset_id = prompt("BigQuery dataset id", dataset_id)?;
                let key_file = prompt(
                    "Path to BigQuery service-account JSON (leave empty to keep the placeholder)",
                    "",
                )?;
                if !key_file.is_empty() && key_file != REPLACE_ME {
                    *service_account_key = fs::read_to_string(&key_file)
                        .with_context(|| format!("Failed to read {key_file}"))?;
                }
            }
            Self::DuckLake { catalog_url, data_path } => {
                *catalog_url = prompt("DuckLake catalog URL", catalog_url)?;
                *data_path = prompt("DuckLake data path (s3://...)", data_path)?;
            }
            Self::Iceberg(IcebergSetup::Rest {
                catalog_uri, warehouse_name, s3_endpoint, ..
            }) => {
                *catalog_uri = prompt("Iceberg catalog URI", catalog_uri)?;
                *warehouse_name = prompt("Iceberg warehouse name", warehouse_name)?;
                *s3_endpoint = prompt("Iceberg S3 endpoint", s3_endpoint)?;
            }
            Self::Iceberg(IcebergSetup::Supabase {
                project_ref,
                warehouse_name,
                s3_region,
                ..
            }) => {
                *project_ref = prompt("Supabase project ref", project_ref)?;
                *warehouse_name = prompt("Iceberg warehouse name", warehouse_name)?;
                *s3_region = prompt("Iceberg S3 region", s3_region)?;
            }
            Self::Snowflake { account_id, user, database, schema, .. } => {
                *account_id = prompt("Snowflake account", account_id)?;
                *user = prompt("Snowflake user", user)?;
                *database = prompt("Snowflake database", database)?;
                *schema = prompt("Snowflake schema", schema)?;
            }
        }

        Ok(())
    }

    /// Renders the destination YAML mapping.
    fn to_yaml(&self) -> String {
        match self {
            Self::ClickHouse { url, user, password } => format!(
                "\
destination:
  clickhouse:
    url: {url}
    user: {user}
    password: {password}
    database: default
",
                url = yaml_string(url),
                user = yaml_string(user),
                password = yaml_string(password),
            ),
            Self::BigQuery { project_id, dataset_id, service_account_key } => {
                let key = service_account_key.trim();
                let key_field = if key.contains('\n') {
                    format!("    service_account_key: |\n      {}\n", key.replace('\n', "\n      "))
                } else {
                    format!("    service_account_key: {}\n", yaml_string(key))
                };
                format!(
                    "\
destination:
  big_query:
    project_id: {project}
    dataset_id: {dataset}
{key_field}",
                    project = yaml_string(project_id),
                    dataset = yaml_string(dataset_id),
                    key_field = key_field,
                )
            }
            Self::DuckLake { catalog_url, data_path } => format!(
                "\
destination:
  ducklake:
    catalog_url: {catalog}
    data_path: {data_path}
",
                catalog = yaml_string(catalog_url),
                data_path = yaml_string(data_path),
            ),
            Self::Iceberg(IcebergSetup::Rest {
                catalog_uri,
                warehouse_name,
                s3_endpoint,
                s3_access_key_id,
                s3_secret_access_key,
            }) => format!(
                "\
destination:
  iceberg:
    rest:
      catalog_uri: {catalog_uri}
      warehouse_name: {warehouse}
      s3_endpoint: {s3_endpoint}
      s3_access_key_id: {access_key}
      s3_secret_access_key: {secret_key}
",
                catalog_uri = yaml_string(catalog_uri),
                warehouse = yaml_string(warehouse_name),
                s3_endpoint = yaml_string(s3_endpoint),
                access_key = yaml_string(s3_access_key_id),
                secret_key = yaml_string(s3_secret_access_key),
            ),
            Self::Iceberg(IcebergSetup::Supabase {
                project_ref,
                warehouse_name,
                s3_region,
                catalog_token,
                s3_access_key_id,
                s3_secret_access_key,
            }) => format!(
                "\
destination:
  iceberg:
    supabase:
      project_ref: {project_ref}
      warehouse_name: {warehouse}
      catalog_token: {catalog_token}
      s3_access_key_id: {access_key}
      s3_secret_access_key: {secret_key}
      s3_region: {region}
",
                project_ref = yaml_string(project_ref),
                warehouse = yaml_string(warehouse_name),
                catalog_token = yaml_string(catalog_token),
                access_key = yaml_string(s3_access_key_id),
                secret_key = yaml_string(s3_secret_access_key),
                region = yaml_string(s3_region),
            ),
            Self::Snowflake { account_id, user, database, schema, private_key } => format!(
                "\
destination:
  snowflake:
    account_id: {account}
    user: {user}
    private_key: {private_key}
    database: {database}
    schema: {schema}
",
                account = yaml_string(account_id),
                user = yaml_string(user),
                private_key = yaml_string(private_key),
                database = yaml_string(database),
                schema = yaml_string(schema),
            ),
        }
    }
}

impl IcebergSetup {
    /// Builds Iceberg catalog defaults for `catalog`.
    fn from_catalog(catalog: IcebergCatalog) -> Self {
        match catalog {
            IcebergCatalog::Rest => Self::Rest {
                catalog_uri: "http://127.0.0.1:8182/catalog".to_owned(),
                warehouse_name: "dev-and-test-warehouse".to_owned(),
                s3_endpoint: "http://127.0.0.1:9010".to_owned(),
                s3_access_key_id: "minio-admin".to_owned(),
                s3_secret_access_key: "minio-admin-password".to_owned(),
            },
            IcebergCatalog::Supabase => Self::Supabase {
                project_ref: "exampleprojectref000".to_owned(),
                warehouse_name: "etl_warehouse".to_owned(),
                s3_region: "us-east-1".to_owned(),
                catalog_token: PLACEHOLDER_ICEBERG_CATALOG_TOKEN.to_owned(),
                s3_access_key_id: PLACEHOLDER_S3_ACCESS_KEY_ID.to_owned(),
                s3_secret_access_key: PLACEHOLDER_S3_SECRET_ACCESS_KEY.to_owned(),
            },
        }
    }
}

/// Writes gitignored local replicator configuration when missing, or when
/// `force` is set.
pub(super) fn write_replicator_config(options: &ReplicatorSetup, force: bool) -> Result<PathBuf> {
    let directory = replicator_config_dir()?;
    ensure_config_dir(&directory)?;

    write_file(&directory.join("base.yaml"), REPLICATOR_BASE_YAML, force)?;
    write_file(&directory.join("dev.yaml"), &options.to_yaml(), force)?;
    Ok(directory)
}

/// Reads the destination kind from generated replicator configuration.
pub(crate) fn detect_replicator_destination(directory: &Path) -> Result<DestinationPreset> {
    let config = load_local_replicator_config(directory)?;
    Ok(preset_from_kind(config.destination.kind()))
}

/// Returns whether generated replicator configuration still contains
/// placeholder secrets after file and environment overrides are applied.
pub(crate) fn replicator_config_has_placeholders(directory: &Path) -> Result<bool> {
    let config = load_local_replicator_config(directory)?;
    Ok(destination_has_placeholders(&config.destination))
}

/// Loads generated local replicator configuration from `directory`.
fn load_local_replicator_config(directory: &Path) -> Result<ReplicatorConfig> {
    let _guard = ConfigEnvGuard::set(directory, "dev");
    etl_config::load_config().with_context(|| {
        format!("Failed to load replicator configuration from {}", directory.display())
    })
}

/// Maps a loaded destination kind onto the local destination preset.
fn preset_from_kind(kind: etl_config::shared::DestinationKind) -> DestinationPreset {
    match kind {
        etl_config::shared::DestinationKind::BigQuery => DestinationPreset::BigQuery,
        etl_config::shared::DestinationKind::ClickHouse => DestinationPreset::ClickHouse,
        etl_config::shared::DestinationKind::Ducklake => DestinationPreset::DuckLake,
        etl_config::shared::DestinationKind::Iceberg => DestinationPreset::Iceberg,
        etl_config::shared::DestinationKind::Snowflake => DestinationPreset::Snowflake,
    }
}

/// Returns whether loaded destination secrets are still generated placeholders.
fn destination_has_placeholders(destination: &DestinationConfig) -> bool {
    match destination {
        DestinationConfig::BigQuery { service_account_key, .. } => {
            service_account_key.expose_secret() == PLACEHOLDER_SERVICE_ACCOUNT_KEY
        }
        DestinationConfig::Snowflake { private_key, .. } => {
            private_key.expose_secret() == PLACEHOLDER_SNOWFLAKE_PRIVATE_KEY
        }
        DestinationConfig::Iceberg {
            config:
                IcebergConfig::Supabase {
                    catalog_token, s3_access_key_id, s3_secret_access_key, ..
                },
        } => {
            catalog_token.expose_secret() == PLACEHOLDER_ICEBERG_CATALOG_TOKEN
                || s3_access_key_id.expose_secret() == PLACEHOLDER_S3_ACCESS_KEY_ID
                || s3_secret_access_key.expose_secret() == PLACEHOLDER_S3_SECRET_ACCESS_KEY
        }
        DestinationConfig::ClickHouse { .. }
        | DestinationConfig::Ducklake { .. }
        | DestinationConfig::Iceberg { config: IcebergConfig::Rest { .. } } => false,
    }
}

/// Temporarily sets config-directory environment variables.
struct ConfigEnvGuard {
    previous_config_dir: Option<OsString>,
    previous_environment: Option<OsString>,
}

impl ConfigEnvGuard {
    /// Sets `APP_CONFIG_DIR` and `APP_ENVIRONMENT` for the lifetime of the
    /// guard.
    fn set(directory: &Path, environment: &str) -> Self {
        let previous_config_dir = env::var_os("APP_CONFIG_DIR");
        let previous_environment = env::var_os("APP_ENVIRONMENT");
        // SAFETY: xtask commands are single-threaded, and nextest runs each
        // test in its own process.
        unsafe {
            env::set_var("APP_CONFIG_DIR", directory);
            env::set_var("APP_ENVIRONMENT", environment);
        }
        Self { previous_config_dir, previous_environment }
    }
}

impl Drop for ConfigEnvGuard {
    fn drop(&mut self) {
        // SAFETY: pairs with [`ConfigEnvGuard::set`] in the same single-threaded
        // command or test process.
        unsafe {
            match &self.previous_config_dir {
                Some(value) => env::set_var("APP_CONFIG_DIR", value),
                None => env::remove_var("APP_CONFIG_DIR"),
            }
            match &self.previous_environment {
                Some(value) => env::set_var("APP_ENVIRONMENT", value),
                None => env::remove_var("APP_ENVIRONMENT"),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_setup(
        destination: DestinationPreset,
        iceberg_catalog: IcebergCatalog,
    ) -> ReplicatorSetup {
        ReplicatorSetup::for_destination(&InitConfig::from_env(), destination, iceberg_catalog)
    }

    fn unique_temp_dir(label: &str) -> PathBuf {
        std::env::temp_dir().join(format!(
            "etl-xtask-{label}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
        ))
    }

    fn write_replicator_yaml(yaml: &str) -> PathBuf {
        let directory = unique_temp_dir("replicator-config");
        fs::create_dir_all(&directory).unwrap();
        fs::write(directory.join("base.yaml"), REPLICATOR_BASE_YAML).unwrap();
        fs::write(directory.join("dev.yaml"), yaml).unwrap();
        directory
    }

    fn load_replicator_yaml(yaml: &str) -> ReplicatorConfig {
        let directory = write_replicator_yaml(yaml);
        let loaded = load_local_replicator_config(&directory)
            .expect("generated replicator config should load");
        let _ = fs::remove_dir_all(&directory);
        loaded
    }

    #[test]
    fn replicator_dev_yaml_uses_fake_bigquery_secret() {
        let yaml = test_setup(DestinationPreset::BigQuery, IcebergCatalog::Rest).to_yaml();
        assert!(yaml.contains("  big_query:"));
        assert!(
            yaml.contains(&format!("service_account_key: \"{PLACEHOLDER_SERVICE_ACCOUNT_KEY}\""))
        );
        assert!(!yaml.contains(REPLACE_ME));
        load_replicator_yaml(&yaml);
    }

    #[test]
    fn replicator_dev_yaml_clickhouse_includes_local_password() {
        let yaml = test_setup(DestinationPreset::ClickHouse, IcebergCatalog::Rest).to_yaml();
        assert!(yaml.contains("  clickhouse:"));
        assert!(yaml.contains("password: \"etl\""));
        load_replicator_yaml(&yaml);
    }

    #[test]
    fn replicator_dev_yaml_ducklake_omits_s3_secrets() {
        let yaml = test_setup(DestinationPreset::DuckLake, IcebergCatalog::Rest).to_yaml();
        assert!(yaml.contains("  ducklake:"));
        assert!(yaml.contains("catalog_url:"));
        assert!(yaml.contains("data_path:"));
        assert!(!yaml.contains("s3_access_key_id"));
        assert!(!yaml.contains("s3_secret_access_key"));
        load_replicator_yaml(&yaml);
    }

    #[test]
    fn replicator_dev_yaml_iceberg_rest_uses_local_catalog() {
        let yaml = test_setup(DestinationPreset::Iceberg, IcebergCatalog::Rest).to_yaml();
        assert!(yaml.contains("  iceberg:"));
        assert!(yaml.contains("    rest:"));
        assert!(yaml.contains("catalog_uri: \"http://127.0.0.1:8182/catalog\""));
        assert!(yaml.contains("warehouse_name: \"dev-and-test-warehouse\""));
        assert!(yaml.contains("s3_endpoint: \"http://127.0.0.1:9010\""));
        assert!(!yaml.contains("supabase:"));
        assert!(!yaml.contains("catalog_token"));
        load_replicator_yaml(&yaml);
    }

    #[test]
    fn replicator_dev_yaml_iceberg_supabase_uses_fake_secrets() {
        let yaml = test_setup(DestinationPreset::Iceberg, IcebergCatalog::Supabase).to_yaml();
        assert!(yaml.contains("  iceberg:"));
        assert!(yaml.contains("    supabase:"));
        assert!(yaml.contains("project_ref: \"exampleprojectref000\""));
        assert!(yaml.contains(&format!("catalog_token: \"{PLACEHOLDER_ICEBERG_CATALOG_TOKEN}\"")));
        assert!(!yaml.contains("    rest:"));
        load_replicator_yaml(&yaml);
    }

    #[test]
    fn replicator_dev_yaml_snowflake_uses_fake_private_key() {
        let yaml = test_setup(DestinationPreset::Snowflake, IcebergCatalog::Rest).to_yaml();
        assert!(yaml.contains("  snowflake:"));
        assert!(yaml.contains("account_id: \"exampleorg-exampleaccount\""));
        assert!(yaml.contains(&format!("private_key: \"{PLACEHOLDER_SNOWFLAKE_PRIVATE_KEY}\"")));
        load_replicator_yaml(&yaml);
    }

    #[test]
    fn detect_replicator_destination_reads_generated_yaml() {
        let yaml = test_setup(DestinationPreset::ClickHouse, IcebergCatalog::Rest).to_yaml();
        let directory = write_replicator_yaml(&yaml);
        let detected = detect_replicator_destination(&directory).unwrap();
        let _ = fs::remove_dir_all(&directory);
        assert_eq!(detected, DestinationPreset::ClickHouse);
    }

    #[test]
    fn replicator_config_has_placeholders_for_generated_bigquery() {
        let yaml = test_setup(DestinationPreset::BigQuery, IcebergCatalog::Rest).to_yaml();
        let directory = write_replicator_yaml(&yaml);
        let has_placeholders = replicator_config_has_placeholders(&directory).unwrap();
        let _ = fs::remove_dir_all(&directory);
        assert!(has_placeholders);
    }

    #[test]
    fn replicator_config_has_no_placeholders_for_clickhouse() {
        let yaml = test_setup(DestinationPreset::ClickHouse, IcebergCatalog::Rest).to_yaml();
        let directory = write_replicator_yaml(&yaml);
        let has_placeholders = replicator_config_has_placeholders(&directory).unwrap();
        let _ = fs::remove_dir_all(&directory);
        assert!(!has_placeholders);
    }
}
