self-hosted-runner:
  labels:
    - blacksmith-2vcpu-ubuntu-2404
    - blacksmith-4vcpu-ubuntu-2404
    - blacksmith-8vcpu-ubuntu-2404
    - blacksmith-8vcpu-ubuntu-2404-arm
    - blacksmith-16vcpu-ubuntu-2404
    - blacksmith-32vcpu-ubuntu-2404
# actionlint 1.7.12 does not yet support GitHub's queued concurrency.
paths:
  .github/workflows/reusable-publish-image.yml:
    ignore:
      - '^unexpected key "queue" for "concurrency" section\.'
