[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\n## [Unreleased]\n\n"
body = "\n{% for release in releases %}\n## [v{{ release.version }}] - {{ release.timestamp | date(\"%Y-%m-%d\") }}\n\n{% if release.commits | length == 0 %}No changes.{% endif %}\n{% for group, commits in release.commits | group_by(attribute=\"group\") %}\n### {{ group | upper_first }}\n{% for commit in commits %}- {{ commit.message | upper_first }}\n{% endfor %}\n\n{% endfor %}\n{% endfor %}"
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^(refactor|ref)", group = "Refactors" },
    { message = "^fix", group = "Bug Fixes" },
    { message = ".*", group = "Miscellaneous" },
]
protect_breaking_commits = true
filter_commits = true
tag_pattern = "v*"
skip_tags = false
topo_order = false
sort_commits = "newest"
