[changelog]
header = """
# Changelog

"""

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^(refactor|ref)", group = "Refactors" },
    { message = "^fix", group = "Bug Fixes" },
    { message = ".*", group = "Miscellaneous" },
]
protect_breaking_commits = true
filter_commits = true
tag_pattern = "v*"
skip_tags = false
topo_order = false
sort_commits = "newest"
