[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
{% if releases is defined -%}
{%- for release in releases %}
## [{{ release.version }}] - {{ release.timestamp | date(format="%Y-%m-%d") }}

{%- if release.commits | length == 0 %}
No changes.
{%- endif %}
{%- for group, commits in release.commits | group_by(attribute="group") %}
{%- if not loop.first %}

{%- endif %}
### {{ group | upper_first }}
{%- for commit in commits %}
- {{ commit.message }}
{%- endfor %}
{%- endfor %}
{%- endfor %}
{%- else %}
## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}

{%- if commits | length == 0 %}
No changes.
{%- endif %}
{%- for group, commits in commits | group_by(attribute="group") %}
{%- if not loop.first %}

{%- endif %}
### {{ group | upper_first }}
{%- for commit in commits %}
- {{ commit.message }}
{%- endfor %}
{%- endfor %}
{%- endif %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^(refactor|ref)", group = "Refactors" },
    { message = "^fix", group = "Bug Fixes" },
    { message = ".*", group = "Miscellaneous" },
]
protect_breaking_commits = true
filter_commits = true
tag_pattern = "v*"
skip_tags = false
topo_order = false
sort_commits = "newest"
