services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT:-5430}:5432"
    volumes:
      # Only mount volume if POSTGRES_DATA_VOLUME is set
      - ${POSTGRES_DATA_VOLUME:-postgres_data}:/var/lib/postgresql/data
    command: >
      postgres
      -N 1000
      -c wal_level=logical
      -c max_wal_senders=100
      -c max_replication_slots=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
