site_name: ETL
site_url: https://supabase.github.io/etl
site_description: Stream your Postgres data anywhere in real-time. Simple Rust building blocks for change data capture (CDC) pipelines.
copyright: Copyright &copy; Supabase
repo_name: supabase/etl
repo_url: https://github.com/supabase/etl
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Tutorials:
      - Overview: tutorials/index.md
      - Your First Pipeline: tutorials/first-pipeline.md
      - Custom Stores and Destinations: tutorials/custom-implementations.md
  - How-to Guides:
      - Overview: how-to/index.md
      - Configure Postgres: how-to/configure-postgres.md
  - Reference:
      - Overview: reference/index.md
  - Explanation:
      - Overview: explanation/index.md
      - Architecture: explanation/architecture.md

theme:
  name: "material"
  favicon: "assets/favicon.ico"
  logo: "assets/etl-logo.png"
  homepage: https://supabase.github.io/etl
  features:
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: material/github
    edit: material/pencil
    view: material/eye

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/supabase
      name: Supabase on Twitter
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/supabase
      name: Supabase on Reddit
    - icon: fontawesome/brands/github
      link: https://github.com/supabase/etl
      name: ETL on GitHub

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      guess_lang: false
      use_pygments: true
      pygments_style: default
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.tasklist
  - admonition

plugins:
  - search
