version: '3.8'

# Docker Compose setup for Iceberg integration tests
# Start with: docker-compose -f docker-compose.test.yml up -d
# Stop with: docker-compose -f docker-compose.test.yml down

services:
  # PostgreSQL source database with logical replication enabled
  postgres-test:
    image: postgres:15-alpine
    container_name: iceberg-postgres-test
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # MinIO for S3-compatible object storage
  minio:
    image: minio/minio:latest
    container_name: iceberg-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Setup MinIO buckets
  minio-setup:
    image: minio/mc:latest
    container_name: iceberg-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/warehouse || true;
      exit 0;
      "

  # Iceberg REST Catalog
  iceberg-rest:
    image: tabulario/iceberg-rest:0.10.0
    container_name: iceberg-rest-catalog
    depends_on:
      postgres-catalog:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    environment:
      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://minio:9000
      CATALOG_S3_ACCESS__KEY__ID: minioadmin
      CATALOG_S3_SECRET__ACCESS__KEY: minioadmin
      CATALOG_S3_PATH__STYLE__ACCESS: "true"
      CATALOG_CATALOG__IMPL: org.apache.iceberg.jdbc.JdbcCatalog
      CATALOG_URI: jdbc:postgresql://postgres-catalog:5432/iceberg
      CATALOG_JDBC_USER: iceberg
      CATALOG_JDBC_PASSWORD: iceberg
    ports:
      - "8181:8181"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/v1/config"]
      interval: 10s
      timeout: 5s
      retries: 20

  # PostgreSQL for Iceberg catalog metadata
  postgres-catalog:
    image: postgres:15-alpine
    container_name: iceberg-postgres-catalog
    environment:
      POSTGRES_DB: iceberg
      POSTGRES_USER: iceberg
      POSTGRES_PASSWORD: iceberg
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iceberg -d iceberg"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  minio-data:
  postgres-catalog-data: