[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-cli-config = { workspace = true, features = ["yaml"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true }