//! Shared support for Multigres integration tests.

use std::{
    ops::{Deref, DerefMut},
    path::PathBuf,
    process::Command,
    time::{Duration, Instant},
};

use etl::{
    config::{PgConnectionConfig, TcpKeepaliveConfig, TlsConfig},
    schema::PgLsn,
};
use etl_postgres::tokio::test_utils::PgDatabase;
use tokio_postgres::Client;

/// Internal PostgreSQL ports generated by the two-cell local provisioner.
const MULTIGRES_POSTGRES_PORTS: [u16; 2] = [25_432, 25_433];
/// Maximum time allowed for a Multigres failover operation.
const MULTIGRES_OPERATION_TIMEOUT: Duration = Duration::from_secs(180);

/// Database connection and operations for Multigres integration tests.
pub(crate) struct Multigres {
    /// Current database connection through the multigateway.
    database: PgDatabase<Client>,
}

impl Multigres {
    /// Connects to Multigres.
    pub(crate) async fn new() -> Self {
        Self { database: connect_database(gateway_config()).await }
    }

    /// Waits until the standby failover slot confirms at least `target_lsn`.
    pub(crate) async fn wait_for_synchronized_failover_slot(
        &self,
        slot_name: &str,
        target_lsn: PgLsn,
    ) {
        let started_at = Instant::now();
        while !standby_slot_reached(slot_name, target_lsn).await {
            assert!(
                started_at.elapsed() <= MULTIGRES_OPERATION_TIMEOUT,
                "Timed out waiting for the Multigres failover slot to reach {target_lsn}"
            );
            tokio::time::sleep(Duration::from_millis(200)).await;
        }
    }

    /// Switches the Multigres primary and reconnects through the multigateway.
    pub(crate) async fn failover(&mut self) {
        let status = tokio::task::spawn_blocking(|| {
            Command::new("docker")
                .args(["compose", "-f"])
                .arg(compose_file())
                .args([
                    "exec",
                    "-T",
                    "multigres",
                    "multigres",
                    "cluster",
                    "switch-primary",
                    "--config-path",
                    "/multigres/cluster",
                    "--database",
                    "postgres",
                    "--reason",
                    "ETL pipeline Multigres failover test",
                    "--yes",
                ])
                .status()
                .unwrap()
        })
        .await
        .unwrap();

        assert!(status.success());
        self.database = connect_database(self.database.config.clone()).await;
    }

    /// Drops one inactive replication slot through the multigateway.
    pub(crate) async fn drop_replication_slot(&self, slot_name: &str) {
        drop_replication_slot(slot_name).await;
    }
}

impl Deref for Multigres {
    type Target = PgDatabase<Client>;

    fn deref(&self) -> &Self::Target {
        &self.database
    }
}

impl DerefMut for Multigres {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.database
    }
}

/// Returns an environment variable or its local-test default.
fn env_or(key: &str, default: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| default.to_owned())
}

/// Builds the ETL source connection configuration for the multigateway.
fn gateway_config() -> PgConnectionConfig {
    PgConnectionConfig {
        host: env_or("MULTIGRES_GW_HOST", "127.0.0.1"),
        hostaddr: None,
        port: env_or("MULTIGRES_GW_PORT", "15432").parse().unwrap(),
        name: env_or("MULTIGRES_GW_DBNAME", "postgres"),
        username: env_or("MULTIGRES_GW_USER", "postgres"),
        password: Some(env_or("MULTIGRES_GW_PASSWORD", "postgres").into()),
        tls: TlsConfig { enabled: false, trusted_root_certs: String::new() },
        keepalive: TcpKeepaliveConfig::default(),
    }
}

/// Connects through the multigateway, retrying while no primary is available.
async fn connect_database(config: PgConnectionConfig) -> PgDatabase<Client> {
    let started_at = Instant::now();
    loop {
        if let Ok(database) = PgDatabase::try_connect(config.clone()).await {
            return database;
        }

        assert!(
            started_at.elapsed() <= MULTIGRES_OPERATION_TIMEOUT,
            "Timed out connecting to Multigres"
        );
        tokio::time::sleep(Duration::from_millis(200)).await;
    }
}

/// Returns the absolute path to the dedicated Multigres Compose file.
fn compose_file() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../scripts/docker/docker-compose-multigres.yaml")
}

/// Runs a SQL query directly against one internal PostgreSQL cell.
fn query_internal_postgres(port: u16, query: &str) -> Option<String> {
    let output = Command::new("docker")
        .args(["compose", "-f"])
        .arg(compose_file())
        .args([
            "exec",
            "-T",
            "-e",
            "PGPASSWORD=postgres",
            "multigres",
            "psql",
            "-X",
            "-h",
            "127.0.0.1",
            "-p",
            &port.to_string(),
            "-U",
            "postgres",
            "-d",
            "postgres",
            "-Atc",
            query,
        ])
        .output()
        .unwrap();

    output.status.success().then(|| String::from_utf8(output.stdout).unwrap())
}

/// Returns whether the standby slot is promotion-ready at `target_lsn`.
async fn standby_slot_reached(slot_name: &str, target_lsn: PgLsn) -> bool {
    let slot_name = slot_name.to_owned();
    tokio::task::spawn_blocking(move || {
        let query = format!(
            "select case
                 when not pg_is_in_recovery() then 'primary'
                 when exists (
                     select 1
                     from pg_replication_slots
                     where slot_name = '{slot_name}'
                       and failover
                       and synced
                       and not temporary
                       and invalidation_reason is null
                       and confirmed_flush_lsn >= '{target_lsn}'::pg_lsn
                 ) then 'ready'
                 else 'not-ready'
             end"
        );

        MULTIGRES_POSTGRES_PORTS.iter().any(|port| {
            query_internal_postgres(*port, &query).is_some_and(|output| output.trim() == "ready")
        })
    })
    .await
    .unwrap()
}

/// Drops an inactive replication slot through the multigateway.
async fn drop_replication_slot(slot_name: &str) {
    let slot_name = slot_name.to_owned();
    let status = tokio::task::spawn_blocking(move || {
        Command::new("docker")
            .args(["compose", "-f"])
            .arg(compose_file())
            .args([
                "exec",
                "-T",
                "-e",
                "PGPASSWORD=postgres",
                "multigres",
                "psql",
                "-X",
                "host=127.0.0.1 port=15432 user=postgres dbname=postgres replication=database",
                "-v",
                "ON_ERROR_STOP=1",
                "-c",
                &format!("DROP_REPLICATION_SLOT {slot_name}"),
            ])
            .status()
            .unwrap()
    })
    .await
    .unwrap();

    assert!(status.success());
}
