#!/usr/bin/env bash
set -euo pipefail

DUCKDB_VERSION="1.5.1"
DUCKDB_EXTENSION_REPOSITORY_VERSION="v${DUCKDB_VERSION}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_ROOT="${REPO_ROOT}/vendor/duckdb/extensions"

platforms=()
extensions=("ducklake" "httpfs" "json" "parquet" "postgres_scanner")

usage() {
  cat <<'EOF'
usage: vendor_duckdb_extensions.sh [--output-root DIR] [--platform PLATFORM]...

Fetches DuckDB extensions for the pinned DuckDB version.

options:
  --output-root DIR  Root directory to populate. Defaults to vendor/duckdb/extensions.
                     This is useful for optional local testing; Docker builds
                     override it and fetch extensions inside the image build.
  --platform NAME    Platform to fetch. May be repeated. Defaults to linux_amd64,
                     linux_arm64, osx_amd64, and osx_arm64.
  --help             Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-root)
      OUTPUT_ROOT="$2"
      shift 2
      ;;
    --platform)
      platforms+=("$2")
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ${#platforms[@]} -eq 0 ]]; then
  platforms=("linux_amd64" "linux_arm64" "osx_amd64" "osx_arm64")
fi

VENDOR_ROOT="${OUTPUT_ROOT}/${DUCKDB_VERSION}"
MANIFEST_PATH="${VENDOR_ROOT}/manifest.txt"

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

mkdir -p "${VENDOR_ROOT}"
tmp_manifest="$(mktemp)"

{
  echo "# vendored DuckDB extensions for ${DUCKDB_VERSION}."
  echo "# generated by scripts/vendor_duckdb_extensions.sh."
} > "${tmp_manifest}"

for platform in "${platforms[@]}"; do
  platform_dir="${VENDOR_ROOT}/${platform}"
  mkdir -p "${platform_dir}"

  for extension in "${extensions[@]}"; do
    source_url="https://extensions.duckdb.org/${DUCKDB_EXTENSION_REPOSITORY_VERSION}/${platform}/${extension}.duckdb_extension.gz"
    destination_path="${platform_dir}/${extension}.duckdb_extension"

    curl -fsSL "${source_url}" | gzip -dc > "${destination_path}"
    checksum="$(sha256_file "${destination_path}")"
    printf "%s  %s  %s\n" "${platform}/${extension}.duckdb_extension" "${checksum}" "${source_url}" >> "${tmp_manifest}"
  done
done

mv "${tmp_manifest}" "${MANIFEST_PATH}"
